### ISSUE TITLE
Docs not showing up

### ISSUE THREAD

**Issue by jean** [peterhellberg/hiro#5]
`hiro` is now generating an HTML file containing the correct content, but it's still rendering as a mostly blank page (there's a header, a subtitle, and a little blue box). I thought this was due to `prettify` not loading, so I created #4 to fix that.

However now I'm not even seeing  `run_prettify.js` being requested. I'm not sure whether this due to Github's CDN. If I change to e.g. https://raw.githubusercontent.com/google/code-prettify/7be640cbb18dbc437b0d06a8d2467ae57c6938e5/loader/run_prettify.js it is retrieved, but the CSS _still_ isn't requested.

There's no errors in the browser console; this is on firefox and chrome.

If I delete the script tag which sources `bootstrap.min.css`, the content does appear, and I can toggle display of snippets.

**Comment by peterhellberg** [comment]
Are you using drafter v2.3.0?

**Comment by peterhellberg** [comment]
I’m wondering if the use of integrity checks is causing this issue.

(They should be ignored by browsers that doesn’t support [Subresource Integrity](https://www.w3.org/TR/SRI/))

**Comment by peterhellberg** [comment]
I’ve now tested the latest commit of hiro (61f917ed7310579e0f218f1b6a4a41236ceb6c51) in FirefoxDeveloperEdition, Firefox, Chrome and Safari under OS X and it works just fine.

Are you on Windows or Linux?

**Comment by peterhellberg** [comment]
You are free to open this issue again if the problem still exists
